use STAGE

SELECT * FROM STG_ORDERS so  LIMIT 10

SELECT * FROM STG_ORDERS WHERE ORDER_ID = 1000867 LIMIT 100


# Calculando porcentajes de productos por departamento en una orden
SELECT A.DEPARTMENT, 100*(COUNT(A.DEPARTMENT)/ (
	SELECT COUNT(B.DEPARTMENT) FROM STG_ORDERS B WHERE A.ORDER_ID = B.ORDER_ID AND A.USER_ID = B.USER_ID AND A.ORDER_NUMBER = B.ORDER_NUMBER 
)) FROM STG_ORDERS A WHERE A.ORDER_ID = 1000867 #AND A.USER_ID = 198377
GROUP BY A.DEPARTMENT, A.ORDER_ID,  A.USER_ID,  A.ORDER_NUMBER 