DROP TABLE IF EXISTS ODS_PRODUCTS;

CREATE TABLE ODS_PRODUCTS(
	ID BIGINT NOT NULL AUTO_INCREMENT
	, PRODUCT VARCHAR(252)
	, AISLE VARCHAR(252)
	, DEPARTMENT VARCHAR(252)
	, FROM_CATALOG BOOLEAN
	, PRIMARY KEY(ID)
);


DROP TABLE IF EXISTS ODS_ORDERS;

CREATE TABLE ODS_ORDERS(
	ID INT NOT NULL AUTO_INCREMENT
	, ORDER_ID BIGINT
	, USER_ID BIGINT
	, ORDER_NUMBER INT
	, ORDER_HOUR_OF_DAY SMALLINT
	, ORDER_DOW SMALLINT
	, DAYS_SINCE_PRIOR_ORDER INT
	, ADD_TO_CART_ORDER INT
	, PRODUCT BIGINT
	, PRIMARY KEY (ID)
	, INDEX product_id (PRODUCT)
	, FOREIGN KEY (PRODUCT) REFERENCES ODS_PRODUCTS(ID) ON DELETE RESTRICT
)